//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int ArticleId { get; set; }
        public int MemberId { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public Nullable<int> ArticleCover { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Content { get; set; }
    
        public virtual MediaFile MediaFile { get; set; }
        public virtual Category Category { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
