//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaFile
    {
        public MediaFile()
        {
            this.Article = new HashSet<Article>();
            this.Member = new HashSet<Member>();
        }
    
        public int MediaFileId { get; set; }
        public string FileName { get; set; }
    
        public virtual ICollection<Article> Article { get; set; }
        public virtual ICollection<Member> Member { get; set; }
    }
}
