//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Article = new HashSet<Article>();
            this.Comment = new HashSet<Comment>();
        }
    
        public int MemberId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int UserPhoto { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual ICollection<Article> Article { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual MediaFile MediaFile { get; set; }
    }
}
